name: Test python

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  py:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: passwd
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      matrix:
        python: [ 3.7, 3.8, 3.9 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        apt update
        apt install -y python3-pip libpq-dev python3-dev
        pip3 install pipenv
        pipenv install -d

    - name: python
      run: pipenv run ./runtests
